from collections import namedtuple

from PyQt5.QtWidgets import QSlider, QStyle

GTrackView = namedtuple('gTrack', ["frame", "deleteButton", "selectButton", "hLayout"])


sliderGainStyle = (u"QSlider::groove:horizontal {\n"
                   "    border: 1px solid #999999;\n"
                   "    height: 8px;\n"
                   # /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                   "background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);"
                   "    margin: 2px 0;\n"
                   "}\n"
                   "QSlider::handle:horizontal {\n"
                   "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                   "    border: 1px solid #5c5c5c;\n"
                   "    width: 9px;\n"
                   "    margin: -5px 0;\n "
                   # "/* handle is placed by default on the contents rect of the groove. Expand outside the groove *"
                   "    border-radius: 3px;\n"
                   "}\n"
                   "QSlider::sub-page:horizontal {\n"
                   "    background: #048ccc;\n"
                   "    border: 1px solid #999999;\n"
                   "    height: 5px;\n"
                   # /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                   # "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                   "    margin: 2px 0;\n"
                   "}\n"
                   )
sliderOffsetStyle = (u"QSlider::groove:horizontal {\n"
                     "    border: 1px solid #999999;\n"
                     "    height: 8px;\n"
                     # /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                     "background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);"
                     "    margin: 2px 0;\n"
                     "}\n"
                     "QSlider::handle:horizontal {\n"
                     "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                     "    border: 1px solid #5c5c5c;\n"
                     "    width: 9px;\n"
                     "    margin: -5px 0;\n "
                     # "/* handle is placed by default on the contents rect of the groove. Expand outside the groove *"
                     "    border-radius: 3px;\n"
                     "}\n"
                     # "QSlider::groove:horizontal {\n"
                     # "    background: red;\n"
                     # "    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
                     # "    left: 4px; right: 4px;\n"
                     # "}\n"
                     "QSlider::sub-page:horizontal {\n"
                     "    background:  #05B8CC;\n"
                     "    border: 1px solid #999999;\n"
                     "    height: 8px;\n"
                     # /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                     # "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                     "    margin: 2px 0;\n"
                     "}\n"
                     # "QSlider::sub-page:horizontal {\n"
                     # "    back"
                     # "ground: pink;\n"
                     # "}"
                     )
sliderProgressStyle = (u"QSlider::groove:horizontal {\n"
                     "    border: 1px solid #999999;\n"
                     "    height: 8px;\n"
                     # /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                     "background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);"
                     "    margin: 2px 0;\n"
                     "}\n"
                     "QSlider::handle:horizontal {\n"
                     "    border: 1px solid #5c5c5c;\n"
                     "    width: 0px;\n"
                     "    margin: -5px 0;\n "
                     # "/* handle is placed by default on the contents rect of the groove. Expand outside the groove *"
                     "    border-radius: 3px;\n"
                     "}\n"
                     # "QSlider::groove:horizontal {\n"
                     # "    background: red;\n"
                     # "    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
                     # "    left: 4px; right: 4px;\n"
                     # "}\n"
                     "QSlider::sub-page:horizontal {\n"
                     "    background:  #05B8CC;\n"
                     "    border: 1px solid #999999;\n"
                     "    height: 8px;\n"
                     # /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                     # "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                     "    margin: 2px 0;\n"
                     "}\n"
                     # "QSlider::sub-page:horizontal {\n"
                     # "    back"
                     # "ground: pink;\n"
                     # "}"
                     )
progressBarStyle = (u"QProgressBar::chunk {\n"
                    "    background-color: #05B8CC;\n"
                    "    width: 1px;\n"
                    # "    border: 1px solid black;\n"
                    "    border-radius: 5px;\n"
                    "}\n"
                    "QProgressBar {\n"
                    "    border: 1px solid grey;\n"
                    "    border-radius: 5px;\n"
                    # "    text-align: center;\n"
                    "    width: 100px;\n"
                    "}")

buttonStyle = (u"QPushButton{\n"
               # "    background-color: grey;\n"
               "    border-style: outset;\n"
               "    border-width: 2px;\n"
               "    border-radius: 10px;\n"
               # "    border-color: black;\n"
               "    padding: 6px;\n"
               "}\n"
               "QPushButton:hover {\n"
               "    background-color: rgb(100, 100, 100);\n"
               "    border-style: outset;\n"
               "    border-width: 2px;\n"
               "    border-radius: 10px;\n"
               "    border-color: #1e1e1e;"
               "}"
               "QPushButton:pressed {\n"
               "    background-color: rgb(224, 0, 0);\n"
               "    border-style: inset;\n"
               "}")

selectedButtonStyle = (u"QPushButton{\n"
                       "    background-color: grey;\n"
                       "    border-style: outset;\n"
                       "    border-width: 2px;\n"
                       "    border-radius: 10px;\n"
                       # "    border-color: black;\n"
                       "    padding: 6px;\n"
                       "}\n"
                       "QPushButton:pressed {\n"
                       "    background-color: rgb(224, 0, 0);\n"
                       "    border-style: inset;\n"
                       "}")

selectTrackButtonStyle = (u"QPushButton{\n"
                          #  "    background-color: grey;\n"
                          "    border-style: outset;\n"
                          "    border-width: 2px;\n"
                          "    border-radius: 1px;\n"
                          # "    border-color: red;\n"
                          "    border: none;\n"
                          "    padding: 6px;\n"
                          "}\n"
                          "QPushButton:hover {\n"
                          "    background-color: rgb(100, 100, 100);\n"
                          "}"
                          "QPushButton:pressed {\n"
                          "    background-color: rgb(224, 0, 0);\n"
                          "    border-style: inset;\n"
                          "}")

buttonStyle3 = (u"QPushButton{\n"
                "    background-color: grey;\n"
                "    border-style: inset;\n"
                "    border-width: 1px;\n"
                # "    border-radius: 1px;\n"
                "    border-color: black;\n"
                "    border: none;\n"
                "    padding: 6px;\n"
                "}\n"
                "QPushButton:hover {\n"
                "    background-color: rgb(144, 0, 0);\n"
                "}"
                "QPushButton:pressed {\n"
                "    background-color: rgb(224, 0, 0);\n"
                "}")

selectedTrackStyle = (u"QPushButton{\n"
                      "    background-color: grey;\n"
                      "    border-style: inset;\n"
                      "    border-width: 1px;\n"
                      # "    border-radius: 1px;\n"
                      "    border-color: black;\n"
                      "    border: none;\n"
                      "    padding: 6px;\n"
                      "}")

playButtonReadyStyle = (u"QPushButton{\n"
                        "    background-color: #05B8CC;\n"
                        "    border-style: outset;\n"
                        "    border-width: 2px;\n"
                        "    border-radius: 10px;\n"
                        # "    border-color: black;\n"
                        "    padding: 6px;\n"
                        "}\n"
                        "QPushButton:hover {\n"
                        "    background-color: rgb(100, 100, 100);\n"
                        "    border-style: outset;\n"
                        "    border-width: 2px;\n"
                        "    border-radius: 10px;\n"
                        "    border-color: #1e1e1e;"
                        "}"
                        "QPushButton:pressed {\n"
                        "    background-color: rgb(224, 0, 0);\n"
                        "    border-style: inset;\n"
                        "}")
